CREATE TABLE IF NOT EXISTS products (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    prod_name TEXT NOT NULL,
    base_price INTEGER NOT NULL,
    profit INTEGER NOT NULL,
    unit_price INTEGER NOT NULL
)